# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
  exporters:
    otlp/honeycomb:
      endpoint: https://api.honeycomb.io:443
      headers:
        "x-honeycomb-team": ""

processors:
  probabilistic_sampler:
    sampling_percentage: 5 # Samples 5% of traces

#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]
